TRUNCATE TABLE trainers RESTART IDENTITY CASCADE;

-- Insert data into the trainers table
INSERT INTO trainers (
    first_name, 
    last_name, 
    email, 
    phone, 
    country, 
    city, 
    address, 
    gender, 
    date_of_birth, 
    personal_img_url, 
    last_academic_qualification, 
    total_professional_experience, 
    current_employer_name, 
    total_training_delivery_experience, 
    social_media_link, 
    identity_document_img_url, 
    last_education_degree_img_url, 
    video_url, 
    message, 
    is_approved, 
    is_active, 
    created_at, 
    updated_at
) VALUES 
(
    'John', 
    'Doe', 
    'john.doe@example.com', 
    '123-456-7890', 
    'Pakistan', 
    'Karachi', 
    '123 Main St, Apt 4B', 
    'Male', 
    '1985-04-12', 
    'https://firebasestorage.googleapis.com/v0/b/sdc-dashboard-3d2d3.appspot.com/o/SDC%2Fimages%2FcertificateDetails.jpeg?alt=media&token=f91b40c6-bb67-49cc-bfe3-bf793a0a1d34', 
    'Master of Computer Science', 
    10, 
    'TechCorp Inc.', 
    5, 
    'https://linkedin.com/in/johndoe', 
    'https://example.com/images/john_doe_identity.jpg', 
    'https://example.com/images/john_doe_degree.jpg', 
    'https://example.com/videos/john_doe_intro.mp4', 
    'Passionate about teaching the next generation of developers.', 
    false, 
    true, 
    NOW(), 
    NOW()
),
(
    'Jane', 
    'Smith', 
    'jane.smith@example.com', 
    '987-654-3210', 
    'Pakistan', 
    'Lahore', 
    '456 Queen St, Apt 7C', 
    'Female', 
    '1990-09-25', 
    'https://firebasestorage.googleapis.com/v0/b/sdc-dashboard-3d2d3.appspot.com/o/SDC%2Fimages%2FcertificateDetails.jpeg?alt=media&token=f91b40c6-bb67-49cc-bfe3-bf793a0a1d34', 
    'Bachelor in Information Technology', 
    8, 
    'Innovatech Ltd.', 
    4, 
    'https://linkedin.com/in/janesmith', 
    'https://example.com/images/jane_smith_identity.jpg', 
    'https://example.com/images/jane_smith_degree.jpg', 
    'https://example.com/videos/jane_smith_intro.mp4', 
    'Committed to fostering a collaborative learning environment.', 
    false, 
    true, 
    NOW(), 
    NOW()
),
(
    'Michael', 
    'Johnson', 
    'michael.johnson@example.com', 
    '456-789-0123', 
    'Canada', 
    'Toronto', 
    '789 King St, Apt 9D', 
    'Male', 
    '1988-11-20', 
    'https://firebasestorage.googleapis.com/v0/b/sdc-dashboard-3d2d3.appspot.com/o/SDC%2Fimages%2FcertificateDetails.jpeg?alt=media&token=f91b40c6-bb67-49cc-bfe3-bf793a0a1d34', 
    'PhD in Data Science', 
    12, 
    'DataWorks Ltd.', 
    6, 
    'https://linkedin.com/in/michaeljohnson', 
    'https://example.com/images/michael_johnson_identity.jpg', 
    'https://example.com/images/michael_johnson_degree.jpg', 
    'https://example.com/videos/michael_johnson_intro.mp4', 
    'Driven to unlock the potential of data.', 
    true, 
    true, 
    NOW(), 
    NOW()
),
(
    'Emily', 
    'Brown', 
    'emily.brown@example.com', 
    '321-654-0987', 
    'Australia', 
    'Sydney', 
    '123 Harbour St, Apt 2A', 
    'Female', 
    '1992-02-15', 
    'https://firebasestorage.googleapis.com/v0/b/sdc-dashboard-3d2d3.appspot.com/o/SDC%2Fimages%2FcertificateDetails.jpeg?alt=media&token=f91b40c6-bb67-49cc-bfe3-bf793a0a1d34', 
    'Master of Information Systems', 
    9, 
    'SysTech Solutions', 
    5, 
    'https://linkedin.com/in/emilybrown', 
    'https://example.com/images/emily_brown_identity.jpg', 
    'https://example.com/images/emily_brown_degree.jpg', 
    'https://example.com/videos/emily_brown_intro.mp4', 
    'Enthusiastic about innovative technologies.', 
    false, 
    true, 
    NOW(), 
    NOW()
),
(
    'David', 
    'Williams', 
    'david.williams@example.com', 
    '789-012-3456', 
    'India', 
    'Mumbai', 
    '789 Marine Dr, Apt 3E', 
    'Male', 
    '1987-07-30', 
    'https://firebasestorage.googleapis.com/v0/b/sdc-dashboard-3d2d3.appspot.com/o/SDC%2Fimages%2FcertificateDetails.jpeg?alt=media&token=f91b40c6-bb67-49cc-bfe3-bf793a0a1d34', 
    'Bachelor''s in Computer Engineering', 
    11, 
    'TechWave Pvt. Ltd.', 
    7, 
    'https://linkedin.com/in/davidwilliams', 
    'https://example.com/images/david_williams_identity.jpg', 
    'https://example.com/images/david_williams_degree.jpg', 
    'https://example.com/videos/david_williams_intro.mp4', 
    'Focused on bridging the gap between theory and practice.', 
    true, 
    true, 
    NOW(), 
    NOW()
);
